background {{base16.base00.default.hex}}
foreground {{colors.on_background.default.hex}}

cursor {{colors.on_background.default.hex}}

selection_background {{colors.on_primary_fixed.default.hex}}
selection_foreground {{colors.on_background.default.hex}}

# Black
color0 #0d1117
color8 #171b22

# Red
color1 #ff7b72
color9 #ffa198

# Green
color2 #3fb950
color10 #56d364

# Yellow
color3 #d29922
color11 #e3b341

# Blue
color4 #58a6ff
color12 #79c0ff

# Magenta
color5 #bc8cff
color13 #d2a8ff

# Cyan
color6 #75e3ea
color14 #b3f0ff

# White
color7 #b1bac4
color15 #b1bac4
