background #101417
foreground #e0e3e8
cursor #cbe6ff
selection_background #001e30
selection_foreground #cbe6ff

# Black
color0 #8b9198
color8 #41474d

# Red
color1 #ffb4ab
color9 #93000a

# Green
color2 #d0bfe8
color10 #ecdcff

# Yellow
color3 #b8c8d9
color11 #d4e4f6

# Blue
color4 #97ccf8
color12 #014b71

# Magenta
color5 #b8c8d9
color13 #394956

# Cyan
color6 #ecdcff
color14 #d0bfe8

# White
color7 #e0e3e8
color15 #c1c7ce

# Tab bar colors
active_tab_foreground   #00344f
active_tab_background   #97ccf8
inactive_tab_foreground #c1c7ce
inactive_tab_background #1c2024
