hl.curve("durma",        { type = "bezier", points = { {1, 1},      {1, 1}      } })
hl.curve("firlat",       { type = "bezier", points = { {0.25, 1},   {0.5, 1}    } })
hl.curve("firlama",      { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("wind",         { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0}  } })
hl.curve("winIn",        { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.01} } })
hl.curve("winOut",       { type = "bezier", points = { {0.7, 0},    {0.1, 1.0}  } })
hl.curve("linear",       { type = "bezier", points = { {0.0, 0.0},  {1.0, 1.0}  } })
hl.curve("liner",        { type = "bezier", points = { {1, 1},      {1, 1}      } })
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5},  {0.75, 1.0} } })

hl.animation({ leaf = "windows",          enabled = true, speed = 10,   bezier = "wind",        style = "slide"         })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 10,   bezier = "winIn",       style = "popin 80%"     })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 4,    bezier = "firlat",      style = "slide bottom"  })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 5,    bezier = "firlat",      style = "slide bottom"  })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 4,    bezier = "winIn",       style = "slide"         })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 4,    bezier = "wind",        style = "slide"         })
hl.animation({ leaf = "border",           enabled = true, speed = 1,    bezier = "liner"                                })
hl.animation({ leaf = "borderangle",      enabled = true, speed = 60,   bezier = "durma",       style = "loop"          })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 5,    bezier = "wind",        style = "slide"         })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 5,    bezier = "wind",        style = "slidefadevert" })
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 1.73, bezier = "almostLinear"                         })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 1.46, bezier = "almostLinear"                         })
hl.animation({ leaf = "fade",             enabled = true, speed = 3.03, bezier = "almostLinear"                         })

